# Notification emails
target_email_address: "c.wingfield@lancaster.ac.uk"
email_connection_details: "/Users/caiwingfield/Resilio Sync/Resilio Sync Lancaster/notify@cwcomplex.net.txt"

# Data directories
graphs_dir:             "/Volumes/Big Data/graphs"

node_distributions_dir: "/Volumes/Big Data/node_distributions/"

output_dir:             "/Volumes/Big Data/spreading activation model/Model output/"
evaluation_dir:         "/Volumes/Big Data/spreading activation model/Evaluation/"
ancillary_dir:          "/Volumes/Big Data/spreading activation model/Ancillary results/"
figures_dir:            "/Volumes/Big Data/spreading activation model/Figures/"
